### PR TITLE
Add Swift 4 support

### PR DESCRIPTION
**Pull request by quanvo87**

### CODE REVIEW

**Comment by youming-lin** [comment]
IBM-Swift/Kitura#1121

**Review by youming-lin — APPROVED** [review]

**Comment by shmuelk** [comment]
We haven't used CHiredis in a very long time. It was used in much older versions of our Swift Redis implementation.

**Comment by quanvo87** [comment]
Should this be deprecated?

**Comment by youming-lin** [comment]
I think so. The repo traffic shows 0 downloads except for this PR.

**Pull request merged**
